// <auto-generated />
namespace OrderFoodOnline.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class pictureurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pictureurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201504140830346_pictureurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
